theme: minima

# Site Settings
title:               davidr's blog

paginate:            5

minima:
  skin: solarized-dark
  social_links: 
  - url: https://x.com/daviddavid
    title: x.com/daviddavid
    icon: twitter
  - url: https://jp.linkedin.com/in/david-maria-r%25C3%25B6hrscheid-62919659
    title: LinkedIn
    icon: linkedin


