# Site Settings
title:               David M. Röhrscheid
tagline:             blog
description:
baseurl:            #"/"
url:                #"davidr.co"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "David M. Röhrscheid"
  twitter:           "daviddavid"
  instagram:         "mrdaviddavid"
  github:            "mrdavid"
#  facebook:          "Le.Paul.94"
#  linkedin:          "lenpaul"
navigation:
- title: Blog
  url: /
- title: About
  url: /menu/cv
- title: Book Log
  url: https://github.com/mrdavid/Buchnotizen/blob/master/README.md
#- title: Contact
#  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
plugins:                [jekyll-paginate]
