theme: minima

# Site Settings
title:               davidr's blog
description:
author:
  name:              "David M. Röhrscheid"

paginate:            5

minima:
  skin: solarized
  social_links: 
    twitter:
      url: https://x.com/daviddavid
      title: x.com/daviddavid
      icon: twitter
    linkedin:
      url: https://jp.linkedin.com/in/david-maria-r%25C3%25B6hrscheid-62919659
      title: LinkedIn
      icon: linkedin


