theme: minima

# Site Settings
title:               David M. Röhrscheid
tagline:             blog
description:
author:
  name:              "David M. Röhrscheid"
  twitter:           "daviddavid"
  github:            "mrdavid"
  linkedin:          "david-maria-röhrscheid-62919659"
  #youtube:            "DavidMariaRoehrscheid"
navigation:
- title: Blog
  url: /
- title: About
  url: /menu/cv
- title: Book Log
  url: https://github.com/mrdavid/Buchnotizen/blob/master/README.md

paginate:            5

minima:
  skin: solarized
